### ISSUE TITLE
Inline style

### ISSUE THREAD

**Issue by klementj** [witwitwut/FilmSiteDb#1]
https://github.com/witwitwut/FilmSiteDb/blob/8886b87a165632b33593f48f01dfe3200feef44b/src/index.html#L30

Vær opmærksom på når du copy paster hvad der kommer med. Her er der kommet inline style med. Hvilke vi ikke vil have!

**Comment by witwitwut** [comment]
jeg gjorde det men jeg gjorde fordi jeg ville, #rebelForLife
